### ISSUE TITLE
Add documentation to migarate from `v2.0.x` to `v3.0.x`

### ISSUE THREAD

**Issue by princ3od** [sososdk/flash#62]
Recently, `v3.0.0` and `v3.0.1` have just been released, which completely changed the package's APIs. As there are no release notes, it is very difficult to migrate from `v2.0.x` to `v3.0.x`. 
For example: `{context}.showFlashBar(..)` and `context.showFlashDialog(..)` can not be found in `v3.0.x`.

Thank you for putting effort into creating this great package!

One minor feat: could you please add a callback for `onBarrierTap` as well? I can help on this feat after migrating to `v3.0.x`

**Comment by sososdk** [comment]
Using `context.showFlash` instead `context.showFlashBar` and  `context.showFlashDialog` in `v3.0.x`.

Show a flash bar, please refer to: 
https://github.com/sososdk/flash/blob/b0e01725f62c919dad90d7b7bc5aebe1873ad513/example/lib/main.dart#L254

Show a flash dialog, please refer to: 
https://github.com/sososdk/flash/blob/b0e01725f62c919dad90d7b7bc5aebe1873ad513/example/lib/main.dart#L335

You can try `onBarrierTap` on:
```yaml
dependencies:
  flash:
    git:
      url: https://github.com/sososdk/flash.git
      ref: 7f0effc2db9c829254dcf659507b437ac9fa8178
```
